---
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: backup-example
spec:
  method: plugin
  cluster:
    name: cluster-pgbackrest
  pluginConfiguration:
    name: pgbackrest.dalibo.com
