---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-sample
spec:
  # set to Never, because we use kind and image should be loaded on
  # the Kubernetes cluster and not pulled from an external registry.
  imagePullPolicy: IfNotPresent
  instances: 1
  plugins:
    - name: pgbackrest.dalibo.com
      enabled: true
      isWALArchiver: true
      parameters:
        stanzaRef: stanza-sample
        pluginConfigRef: sample-pluginconfig
  storage:
    size: 1Gi
