---
apiVersion: v1
kind: Secret
metadata:
  name: minio
type: Opaque
stringData:
  ACCESS_KEY_ID: minioKey
  ACCESS_SECRET_KEY: minioKey
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-demo
spec:
  # set to Never, because we use kind and image should be loaded on
  # the Kubernetes cluster and not pulled from an external registry.
  imagePullPolicy: IfNotPresent
  instances: 1
  plugins:
    - name: pgbackrest.dalibo.com
      enabled: true
      isWALArchiver: true
      parameters:
        repositoryRef: repository-sample
  storage:
    size: 1Gi
