---
apiVersion: v1
kind: Secret
metadata:
  name: pgbackrest-s3-secret
type: Opaque
stringData:
  key: xxx
  key-secret: xxx
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-demo
spec:
  # set to Never, because we use kind and image should be loaded on
  # the Kubernetes cluster and not pulled from an external registry.
  imagePullPolicy: Never
  instances: 1
  plugins:
    - name: pgbackrest.dalibo.com
      parameters:
        s3-bucket: demo-pgbackrest
        s3-endpoint: xxx
        s3-region: xxx
        s3-repo-path: /demo-pgbackrest-4/cluster-demo
        stanza: pgbackrest
  storage:
    size: 1Gi
