---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: backup-example
spec:
  schedule: "0 15 * * * *"
  method: plugin
  cluster:
    name: cluster-demo
  pluginConfiguration:
    name: pgbackrest.dalibo.com
