---
apiVersion: v1
kind: Secret
metadata:
  name: garage
type: Opaque
stringData:
  ACCESS_KEY_ID: GKea245649c77084aff46e056a
  ACCESS_SECRET_KEY: 552481d0d728e40190ec8ef219986f5ace854454a3fdf2e93ed6693efbf60d08
  ENCRYPTION_PASS: 3nCryptI0nk3y

