//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 Dalibo <contact@dalibo.com>
//
// SPDX-License-Identifier: Apache-2.0
/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package api

import (
	pkgapi "github.com/cloudnative-pg/machinery/pkg/api"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArchiveOption) DeepCopyInto(out *ArchiveOption) {
	*out = *in
	if in.PushQueueMax != nil {
		in, out := &in.PushQueueMax, &out.PushQueueMax
		*out = new(string)
		**out = **in
	}
	if in.GetQueueMax != nil {
		in, out := &in.GetQueueMax, &out.GetQueueMax
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArchiveOption.
func (in *ArchiveOption) DeepCopy() *ArchiveOption {
	if in == nil {
		return nil
	}
	out := new(ArchiveOption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Repository) DeepCopyInto(out *Repository) {
	*out = *in
	if in.S3Repositories != nil {
		in, out := &in.S3Repositories, &out.S3Repositories
		*out = make([]S3Repository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Archive.DeepCopyInto(&out.Archive)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Repository.
func (in *Repository) DeepCopy() *Repository {
	if in == nil {
		return nil
	}
	out := new(Repository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Retention) DeepCopyInto(out *Retention) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Retention.
func (in *Retention) DeepCopy() *Retention {
	if in == nil {
		return nil
	}
	out := new(Retention)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Repository) DeepCopyInto(out *S3Repository) {
	*out = *in
	if in.VerifyTLS != nil {
		in, out := &in.VerifyTLS, &out.VerifyTLS
		*out = new(bool)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretRef)
		(*in).DeepCopyInto(*out)
	}
	out.RetentionPolicy = in.RetentionPolicy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Repository.
func (in *S3Repository) DeepCopy() *S3Repository {
	if in == nil {
		return nil
	}
	out := new(S3Repository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
	if in.AccessKeyIDReference != nil {
		in, out := &in.AccessKeyIDReference, &out.AccessKeyIDReference
		*out = new(pkgapi.SecretKeySelector)
		**out = **in
	}
	if in.SecretAccessKeyReference != nil {
		in, out := &in.SecretAccessKeyReference, &out.SecretAccessKeyReference
		*out = new(pkgapi.SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}
