//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 Dalibo <contact@dalibo.com>
//
// SPDX-License-Identifier: Apache-2.0
/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package api

import (
	pkgapi "github.com/cloudnative-pg/machinery/pkg/api"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Archive) DeepCopyInto(out *Archive) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Archive.
func (in *Archive) DeepCopy() *Archive {
	if in == nil {
		return nil
	}
	out := new(Archive)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArchiveOption) DeepCopyInto(out *ArchiveOption) {
	*out = *in
	if in.PushQueueMax != nil {
		in, out := &in.PushQueueMax, &out.PushQueueMax
		*out = new(string)
		**out = **in
	}
	if in.GetQueueMax != nil {
		in, out := &in.GetQueueMax, &out.GetQueueMax
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArchiveOption.
func (in *ArchiveOption) DeepCopy() *ArchiveOption {
	if in == nil {
		return nil
	}
	out := new(ArchiveOption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureRepository) DeepCopyInto(out *AzureRepository) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(AzureSecretRef)
		(*in).DeepCopyInto(*out)
	}
	if in.VerifyTLS != nil {
		in, out := &in.VerifyTLS, &out.VerifyTLS
		*out = new(bool)
		**out = **in
	}
	out.RetentionPolicy = in.RetentionPolicy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureRepository.
func (in *AzureRepository) DeepCopy() *AzureRepository {
	if in == nil {
		return nil
	}
	out := new(AzureRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureSecretRef) DeepCopyInto(out *AzureSecretRef) {
	*out = *in
	if in.KeyReference != nil {
		in, out := &in.KeyReference, &out.KeyReference
		*out = new(pkgapi.SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureSecretRef.
func (in *AzureSecretRef) DeepCopy() *AzureSecretRef {
	if in == nil {
		return nil
	}
	out := new(AzureSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupData) DeepCopyInto(out *BackupData) {
	*out = *in
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = make([]BackupInfo, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupData.
func (in *BackupData) DeepCopy() *BackupData {
	if in == nil {
		return nil
	}
	out := new(BackupData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupInfo) DeepCopyInto(out *BackupInfo) {
	*out = *in
	out.Archive = in.Archive
	out.Lsn = in.Lsn
	out.Timestamp = in.Timestamp
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupInfo.
func (in *BackupInfo) DeepCopy() *BackupInfo {
	if in == nil {
		return nil
	}
	out := new(BackupInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CipherConfig) DeepCopyInto(out *CipherConfig) {
	*out = *in
	if in.PassReference != nil {
		in, out := &in.PassReference, &out.PassReference
		*out = new(pkgapi.SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CipherConfig.
func (in *CipherConfig) DeepCopy() *CipherConfig {
	if in == nil {
		return nil
	}
	out := new(CipherConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompressConfig) DeepCopyInto(out *CompressConfig) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompressConfig.
func (in *CompressConfig) DeepCopy() *CompressConfig {
	if in == nil {
		return nil
	}
	out := new(CompressConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Lsn) DeepCopyInto(out *Lsn) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Lsn.
func (in *Lsn) DeepCopy() *Lsn {
	if in == nil {
		return nil
	}
	out := new(Lsn)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryWindow) DeepCopyInto(out *RecoveryWindow) {
	*out = *in
	out.FirstBackup = in.FirstBackup
	out.LastBackup = in.LastBackup
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryWindow.
func (in *RecoveryWindow) DeepCopy() *RecoveryWindow {
	if in == nil {
		return nil
	}
	out := new(RecoveryWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Retention) DeepCopyInto(out *Retention) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Retention.
func (in *Retention) DeepCopy() *Retention {
	if in == nil {
		return nil
	}
	out := new(Retention)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Repository) DeepCopyInto(out *S3Repository) {
	*out = *in
	if in.VerifyTLS != nil {
		in, out := &in.VerifyTLS, &out.VerifyTLS
		*out = new(bool)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(S3SecretRef)
		(*in).DeepCopyInto(*out)
	}
	out.RetentionPolicy = in.RetentionPolicy
	if in.Cipher != nil {
		in, out := &in.Cipher, &out.Cipher
		*out = new(CipherConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Repository.
func (in *S3Repository) DeepCopy() *S3Repository {
	if in == nil {
		return nil
	}
	out := new(S3Repository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3SecretRef) DeepCopyInto(out *S3SecretRef) {
	*out = *in
	if in.AccessKeyIDReference != nil {
		in, out := &in.AccessKeyIDReference, &out.AccessKeyIDReference
		*out = new(pkgapi.SecretKeySelector)
		**out = **in
	}
	if in.SecretAccessKeyReference != nil {
		in, out := &in.SecretAccessKeyReference, &out.SecretAccessKeyReference
		*out = new(pkgapi.SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3SecretRef.
func (in *S3SecretRef) DeepCopy() *S3SecretRef {
	if in == nil {
		return nil
	}
	out := new(S3SecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Stanza) DeepCopyInto(out *Stanza) {
	*out = *in
	if in.S3Repositories != nil {
		in, out := &in.S3Repositories, &out.S3Repositories
		*out = make([]S3Repository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AzureRepositories != nil {
		in, out := &in.AzureRepositories, &out.AzureRepositories
		*out = make([]AzureRepository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Archive.DeepCopyInto(&out.Archive)
	if in.Compress != nil {
		in, out := &in.Compress, &out.Compress
		*out = new(CompressConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CustomEnvVar != nil {
		in, out := &in.CustomEnvVar, &out.CustomEnvVar
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Stanza.
func (in *Stanza) DeepCopy() *Stanza {
	if in == nil {
		return nil
	}
	out := new(Stanza)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Timestamp) DeepCopyInto(out *Timestamp) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Timestamp.
func (in *Timestamp) DeepCopy() *Timestamp {
	if in == nil {
		return nil
	}
	out := new(Timestamp)
	in.DeepCopyInto(out)
	return out
}
