---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pgbackrest-controller-client
  namespace: cnpg-system
spec:
  commonName: pgbackrest-controller-client
  duration: 2160h
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: selfsigned-issuer
  renewBefore: 360h
  secretName: pgbackrest-controller-client-tls
  usages:
    - client auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pgbackrest-controller-server
  namespace: cnpg-system
spec:
  commonName: pgbackrest
  dnsNames:
    - pgbackrest
  duration: 2160h
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: selfsigned-issuer
  renewBefore: 360h
  secretName: pgbackrest-controller-server-tls
  usages:
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: cnpg-system
spec:
  selfSigned: {}
