---
name: e2e
on:
  - push
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Install required packages (docker, make,...)
        run: sudo apt install -y make
      - name: Setup Go 1.24.x
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
      - name: Install kind
        run: curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.27.0/kind-linux-amd64
          && chmod +x ./kind && sudo mv ./kind /usr/local/bin/kind
      - name: Display kind version
        run: kind version
      - uses: actions/checkout@v4
      - name: Run e2e tests
        run: make clean-kind-e2e-cluster test-e2e
